version: '2'
services:
  jupyter:
    build: jupyter/
    ports:
      - 8888:8888
    volumes:
      - ./projects:/home/jovyan/work
      - .:/data
    environment:
      GRANT_SUDO: 'yes'

  db:
    build: db/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ainorth

